
font_family Lilex
font_size 12.0

window_border_width 1px
active_border_color #00FF00
inactive_border_color #00FF00

copy_on_select yes

map ctrl+v paste_from_clipboard
map ctrl+z ignore

confirm_os_window_close -1

clipboard_control read-primary read-clipboard
